name: release

on:
  push:
    branches:
      - main

jobs:
  build_sdist:
    name: sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build sdist
        run: pipx run build --sdist

      - name: Check metadata
        run: pipx run twine check dist/*

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz

  build_wheels:
    name: ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: manylinux2014_x86_64
            python_version: 3.9
            image: quay.io/pypa/manylinux2014_x86_64

    steps:
      - uses: actions/checkout@v3

      - name: Build Wheels
        run: |
          docker run --rm -v $(pwd):/io ${{matrix.image}}/io/scripts/build_wheel.sh
        env:
          matrix.image: ${{ matrix.image }}
          python_version: ${{ matrix.python_version }}

      - name: Verify clean directory
        run: git diff --exit-code
        shell: bash

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          path: wheelhouse/*.whl

  upload:
    name: upload
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v2

      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - uses: softprops/action-gh-release@v1
        with:
            files: dist/*
            tag_name: v.0.0.2
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Exibir URL de download
        run: echo "URL de Download:https://github.com/${{ github.repository }}/releases/latest"
